name: wan_android_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2

  # State
  provider: ^3.2.0

  # Base Component
  # WebView iOS添加键值对 o.flutter.embedded_views_preview = YES
  webview_flutter: ^0.3.13
  flutter_webview_plugin: ^0.3.8
  device_info: ^0.4.0+1
  package_info: ^0.4.0+6
  quiver: ^2.0.5
  #  connectivity: ^0.4.3+6

  # Data
  #  json_annotation: ^2.4.0
  dio: ^3.0.1
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.0
  shared_preferences: ^0.5.3+5
  # 本地json对象存储
  localstorage: ^2.0.0

  # Html Encoder/Decoder
  html_unescape: ^1.0.1+3
  # 解析html标签
  flutter_html: ^0.10.4

  # 判断list是否相等
  collection: ^1.14.11
  #  crypto: ^2.0.6

  # UI
  oktoast: ^2.1.7
  pull_to_refresh: ^1.5.6
  flutter_swiper: ^1.1.6
  #  cached_network_image: ^1.1.1
  cached_network_image: ^2.0.0-rc.1
  # 类iOS侧滑菜单
  flutter_slidable: 0.5.3
  # 谁用谁闪亮
  shimmer: ^1.0.0
  # 识别图片的主要颜色
  #  palette_generator: ^0.2.0
  # 更新展示支持mark_down
  flutter_markdown: ^0.2.0
  flare_flutter: ^1.5.9

  # third_app
  url_launcher: ^5.1.6 #启动第三方app
  share: 0.6.2+1 #分享
  launch_review: ^2.0.0
  open_file: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
